### ISSUE TITLE
macOS and Windows support

### ISSUE THREAD

**Issue by prettymuchbryce** [jghauser/follow-md-links.nvim#5]
Hello. I installed this plugin on macOS using [LunarVim](https://github.com/LunarVim/LunarVim), which comes with `nvim-treesitter` installed and uses `packer` for managing plugins. I am using NeoVim `v0.6.1`. When I use the plugin and press `<cr>` in normal mode, nothing happens.

Is the plugin expected to work on macOS?
Do you have any suggestions for debugging?

Thanks!

**Comment by jghauser** [comment]
Hey! Thanks for the report. I do only have a Linux machine, so it's very much possible this doesn't work on another OS.

But first, did you check whether you have the required treesitter parser for markdown installed? It might not be installed with nvim-treesitter's default settings (check the installation section of the readme for further information).

If you do have that set up correctly, then it would seem to be some incompatibility with macOS. Does it not work for local links and web links? If it's just web links, then that's probably due to me using `xdg-open` to open them, and maybe macOS doesn't have that installed. If that's the issue, we can try figure out what would be the equivalent there.

**Comment by prettymuchbryce** [comment]
Thanks for the quick reply! I do have the required treesitter parser. I noticed that section of the README and I double checked that I had a ✔️ under the `H` for `markdown`.

I just checked and it appears to work just fine for files, so I think your suspicion of `xdg-open` is correct. The native macOS equivalent is the `open` command. Would it be possible to do a check for the OS and use `open` instead if the system is mac OS? I think this would help open up your plugin to more potential users. 😄

**Comment by jghauser** [comment]
Good we found the problem! Yes, that should absolutely be possible. I'll try implement this later today and will get back to you! :)

**Comment by jghauser** [comment]
Ok, this should be fixed now. Let me know if it works. And if you happen to have a windows machine lying around, would be great to know if it works there too as I tried implementing that also.

**Comment by prettymuchbryce** [comment]
> Ok, this should be fixed now. Let me know if it works.

👏  I can confirm it is now working on Mac OS. Unfortunately I am not knowledgable about Windows, so we may need to find another guinea pig to help us test things there.

**Comment by jghauser** [comment]
Great, thanks! I'm gonna close this, and if it doesn't work for windows I suppose someone will show up haha.
