### ISSUE TITLE
Just saying

### ISSUE THREAD

**Issue by ObserverOfTime** [jghauser/follow-md-links.nvim#7]
The builtin <kbd>gf</kbd> mapping can be used to open files and Netrw provides <kbd>gx</kbd> for links.

**Comment by jghauser** [comment]
Hey! That is right. I think in many instances this plugin isn't really required. I did use `gx` for some time, but I think I stopped because I disabled netrw because of some other conflicting plugin and that stopped working. Another advantage over `gx` and `gf` is that the links will open no matter whether the cursor is over the link label or target.

But yeah, I think in many instances the plugin maybe doesn't add that much... (I actually don't use it all that much anymore as I've mostly moved away from markdown files).
